# Generated by Django 4.1.4 on 2023-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.AddField(
            model_name='avatar',
            name='email_page',
            field=models.EmailField(max_length=75, null=True),
        ),
    ]
